# Generated by Django 3.0.8 on 2020-07-28 09:49

import datetime
from django.db import migrations, models
import keys.models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Item',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('reg_number', models.CharField(blank=True, default=keys.models.increment_reg_number_number, max_length=255, null=True)),
                ('timestamp', models.DateField(default=datetime.datetime.now)),
            ],
            options={
                'ordering': ['-id'],
            },
        ),
    ]
